api:
  key: 2da48326cc6155cf82910357b0091e4890243b127a640e18720f814d1bc04369
  secret: 4a1fd0998a4db54815a71149cf4b46ac7d4f6147884b19e67daaf298ad3bb8445ab39c6291a2eef593de1fbe5a01d1640325d557f355412a84fdd6e1658c11bd
  base-url: "https://api.bitvavo.com"
bitvavo:
  autoSellProfit: 1
  feeType: TAKER
  defaultCurrency: EUR
  endpoints:
    account: "/v2/account"
    asset: "/v2/assets?symbol={0}"
    assets: "/v2/assets"
    market: "/v2/markets?market={0}"
    markets: "/v2/markets"
    order: "/v2/order"
    symbols: "/v2/balance"
    symbol: "/v2/balance?symbol={0}"
    time: "/v2/time"
    tickerPrice: "/v2/ticker/price?market={0}"
    withdrawal: "/v2/withdrawal"
  withdrawAddress: "BE80001813403377"