api:
  key:
  secret:
  base-url: "https://api.bitvavo.com"
bitvavo:
  endpoints:
    account: "/v2/account"
    asset: "/v2/assets?symbol={0}"
    assets: "/v2/assets"
    market: "/v2/markets?market={0}"
    markets: "/v2/markets"
    order: "/v2/order"
    symbols: "/v2/balance"
    symbol: "/v2/balance?symbol={0}"
    tickerPrice: "/v2/ticker/price?market={0}"
    trades: "/v2/trades?market={0}&start={1}"
    withdrawal: "/v2/withdrawal"
  start-timestamp: 1
  withdraw-address: ""
  default-currency: EUR
  fee-type: TAKER
  auto-withdraw-treshold: 100
  auto-sell-treshold: 1
  auto-rebuy: 0
spring:
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptobot
    username: cryptobot
    password: cryptobot
  flyway:
    user: cryptobot_dba
    password: cryptobot_dba
logging:
  level:
    ROOT: error
    be.mathiasbosman.cryptobot: info