api:
  key:
  secret:
  base-url: "https://api.bitvavo.com"
bot:
  start-timestamp: 1
  default-currency: "EUR"
  fee-type: taker
  auto-sell-on-profit: true
bitvavo:
  endpoints:
    account: "/v2/account"
    asset: "/v2/assets?symbol={0}"
    assets: "/v2/assets"
    market: "/v2/markets?market={0}"
    markets: "/v2/markets"
    order: "/v2/order"
    symbols: "/v2/balance"
    symbol: "/v2/balance?symbol={0}"
    tickerPrice: "/v2/ticker/price?market={0}"
    trades: "/v2/trades?market={0}&start={1}"
    withdrawal: "/v2/withdrawal"
  withdraw-address: ""
  auto-withdraw-threshold: 100
spring:
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  datasource:
    url: jdbc:h2:./.db/cryptobot;DATABASE_TO_UPPER=f;
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: Cryptobot
logging:
  level:
    ROOT: error
    be.mathiasbosman.cryptobot: info